### ISSUE TITLE
Application crashes on startup on older devices

### ISSUE THREAD

**Issue by Xenik007** [EricssonResearch/bowser#21]
Hi I am not sure this belongs here so delete it if its not supposed to be here. I have installed bowser from the appstore and it crashes on startup on my ipad 2 with the latest version of iOS 8.1.

**Comment by iachimoe** [comment]
Any updates on this? FYI, I just received the latest upgrade to Bowser on my iPad 3, and it still fails to start properly.

**Comment by stefanalund** [comment]
Sorry @iachimoe we have not had time to look further into this. We know that it's because it takes too long time to start the JavaScript bridge the first time, but we don't have a solution as of now. When running fully native apps on top of OpenWebRTC, there is no such problem since the bridge is not used.

**Comment by zoplonix** [comment]
+1 on iOS 8.1.3 on an iPhone 4s. 

Is there a timeout for how long to wait for the JavaScript bridge to be responsive? If it was increased or removed that may help since the older devices run slower. 

Or is this this an issue of the code hanging itself up or and causing the process to halt? So we have to find where it's getting hung up like not enough memory or missing API or whatever

**Comment by stefanalund** [comment]
The JavaScript bridge takes too long to start and the OS kills the app, at least that is our guess. An interesting experiment would be to execute that piece of init code in a separate thread, using GCD for example.

**Comment by stefanalund** [comment]
That would be `owr_bridge_start_in_thread();` in the AppDelegate.

**Comment by stefanalund** [comment]
I may have a patch that solves this issue, needs a bit more testing before I publish it. :-)

**Comment by stefanalund** [comment]
Seems to work: https://github.com/EricssonResearch/bowser/pull/29

**Comment by stefanalund** [comment]
Just submitted version 0.4 to the App Store. Among other improvements it fixes the startup issue on older devices. If you can't wait for the Apple review you can install Bowser from master using Xcode :)

Let me know if you still see problems and we can re-open this Issue. Thanks for your patience!

**Comment by mccob** [comment]
so OpenWebRTC will me available with 64 bits ?

**Comment by stefanalund** [comment]
Yes @mccob absolutely. We are transitioning over to a new build system called Cerbero, which has support for building iOS on all "platforms" including arm64: https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero

You can get started already now if you would like, the documentation may be a bit sparse still.
