### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by hellothere232** [EricssonResearch/bowser#72]
I can open the website using https, but webrtc won't initialise at all (getusermedia).
Switching to the same site using http works.

**Comment by hellothere232** [comment]
iPhone 5s. Latest version from appstore

**Comment by RobertSmart** [comment]
I'm having the same problem

**Comment by stefanalund** [comment]
Any HTTPS site?

**Comment by Mamong** [comment]
Please try to add these code in OpenWebRTCViewController.m, it will load https request without any challenge.

- (void)webView:(WKWebView *)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler
{
    NSURLCredential* cre = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
    [challenge.sender useCredential:cre forAuthenticationChallenge:challenge];
    completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, cre);
}

**Comment by stefanalund** [comment]
We would be happy to accept a Pull Request from you if you have the possibility.

**Comment by stefanalund** [comment]
@Mamong I added what you suggested in this PR https://github.com/EricssonResearch/openwebrtc-ios-sdk/issues/52 but it does not solve the problem of blocked gUM.

**Comment by stefanalund** [comment]
This has now been fixed in OpenWebRTC and I have submitted a new version 0.6.1 to the App Store for review:

![image1](https://cloud.githubusercontent.com/assets/190856/12949438/1ad47b12-d008-11e5-841c-4bf0a9928113.PNG)

If you want it already now you need to [build OpenWebRTC](https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC) yourself.

Thanks @pererikb for the patch!
